### ISSUE TITLE
Unable to access properties of an Object? 

### ISSUE THREAD

**Issue by jhitchcock** [samskivert/jmustache#73]
This may be purely intended behaviour, but if I am passing a; 

HashMap String, Object

when I iterate the string, I'm unable to access properties of the object. 

if I render {{this}} I see a json object being rendered, (Rather than the key=property I would get usually with mustache) 

Any ideas?

**Comment by samskivert** [comment]
HashMap is not an Iterable and thus will not be treated as a collection by JMustache. If you want to treat it like a collection, you need to put it in the context as "map.entrySet()" which is iterable and will yield things that look like key=property as you expect.

Unfortunately you can't just access the entry set in the script like you might think, with something like:

```
{{#map.entrySet}}{{.}}{{/map.entrySet}}
```

because maps are treated specially by JMustache and looking up keys in them looks them up in the map, rather than doing reflective lookup like JMustache would do on any other normal Java object.
