### ISSUE TITLE
Get unexecuted fragment in lambdas

### ISSUE THREAD

**Issue by YoussefBO** [samskivert/jmustache#75]
Hello there,

You said:
> Currently there is no support for "unexecuting" the template and obtaining the original Mustache template text contained in the section. File a feature request with a sane use case if you have one.

Would this be a use case: I'm currently using [Gnu Gettext](https://www.gnu.org/software/gettext/) and thus have fragments looking like this: `{{#i18n}}Some english text used as the real english text and also as the key.{{/i18n}}` and the lambda looks like this:
```
new Mustache.Lambda() {
	public void execute (Template.Fragment frag, Writer out) throws IOException {
	 	String res = frag.execute();
	 	res = i18n.__(res); // i18n being my translation service
		out.write(res);
	}
}
```

So when I have a fragment looking like this: `{{#i18n}}Hello {{user.name}}.{{/i18n}}`
The msgid in my .pot file will be "Hello {{user.name}}." but when trying to translate, my i18n service will actually look for "Hello Paul." and therefore, find nothing.

Did I miss something? Can I actually get the fragment before it is executed? Or is it the sane use case you were talking about?

Btw, thanks for this great implementation. Been using it with Spring Boot and it works very well.

**Comment by samskivert** [comment]
As the comments indicate, you should be able to make this work now. But you're going to need to do more work than just looking up the decompiled fragment. Now you have to compile (and presumably cache, but you decide how much performance matters) the translated fragment, and then execute the translated fragment (in place of the original fragment) against the context that would normally be used by the lambda.

You might want to only do all that extra work if you see that the decompiled fragment contains a {{ because I'm sure that in most cases, you just have plain text that can be replaced by translated plain text.
