### ISSUE TITLE
Support YAML front matter for templates

### ISSUE THREAD

**Issue by cbeams** [samskivert/jmustache#89]
As described in https://mustache.github.io/mustache.1.html.

See https://github.com/spullara/mustache.java/issues/95#issuecomment-55945821 and https://spring.io/blog/2016/11/21/the-joy-of-mustache-server-side-templates-for-the-jvm#comment-3177111267 for further context.

Cc: @dsyer

**Comment by agentgt** [comment]
@samskivert I think we can safely close this issue for a variety of reasons.

1. I think this may have been desired in the Spring case because JMustache did not originally support inheritance aka layout
2. The Mustache spec is devoid of yaml front matter.
3. Most implementations from my experience pull data from Java objects 
4. This could be done easily with the existing API by users that want this and should not be builtin to avoid dependencies.

@cbeams Do you still want this? Even Handlebars.java is going to be dropping support for this kind of stuff (e.g. using YAML for prototyping).
