### ISSUE TITLE
how to set missingIsNull to be true???

### ISSUE THREAD

**Issue by skcks** [samskivert/jmustache#97]
as title say.....

**Comment by samskivert** [comment]
It's a little weird, but if you just want missing values to return null, you can use:

```
Mustache.compiler().defaultValue(null)
```

to get a compiler that will return `null` for missing values. The default value is also used when a value resolves to `null`, but in this case since the default value is also `null`, it's not actually changing anything for that case.

**Comment by skcks** [comment]
I want to disable throw Exception when missing value, how to do this? @samskivert
